# Generated by Django 5.0.1 on 2024-01-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketosite', '0005_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], max_length=10),
        ),
    ]
